// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.6.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

String calculateFibonacci({required int n}) =>
    RustLib.instance.api.crateApiSimpleCalculateFibonacci(n: n);

String heavyCompute({required int size}) =>
    RustLib.instance.api.crateApiSimpleHeavyCompute(size: size);
